Issue #2037231 - Set geotools logger to Logback for viz
- Changing geotools logger factory to LogbackLoggerFactory due to issues with log level.
- This fixes the following error from geotools while loading shape files:
ERROR 2024-10-30 11:53:21,660 8793 [Worker-13: Retrieving map...] shapefile: Unknown Priority FINEST
java.io.IOException: Unknown Priority FINEST

Change-Id: I6c5be4a72e3430c3d8997ae50c2ca61b87b42650